language: java
sudo: required
jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7
  - oraclejdk8
before_install:
  - if [ `uname -m` = x86_64 ]; then sudo apt-get update -qq && sudo apt-get install -f -q --force-yes ia32-libs ia32-libs-multiarch; fi
